workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: BeTaller
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.glowup.boyuzatmaApp.33JY92T594
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build iOS release
        script: |
          flutter build ios --release --no-codesign
      - name: Package IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - samtehhh@gmail.com
